version: "3.9"

services:
  gpt4free-ts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt4free-ts
    image: gpt4free-ts:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      #      - TZ=Asia/Shanghai
      - http_proxy=http://192.168.0.155:10811
      - https_proxy=http://192.168.0.155:10811
